### ISSUE TITLE
can't bind keys in vivis mode

### ISSUE THREAD

**Issue by wis** [b4b4r07/zsh-vi-mode-visual#10]
Hi Masaki, thanks so much for creating this, it's awesome.
I promise and assure you that I read all the relevant [docs](https://github.com/b4b4r07/zsh-vimode-visual/blob/master/README.md) and [manuals](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html) before opening this issue.
I tried just binding  `o` to what `l` does, with:
`bindkey -M vivis 'o' vi-visual-forward-char`
and it didn't work, I tried unbinding it first
```
bindkey -M vivis -r 'o'
bindkey -M vivis 'o' vi-visual-forward-char
```
and it still doesn't work, how do I know that it's not binded? I ran:
`bindkey -M vivis` and found in the output that `o` is still in it's default binding (`"o" vi-visual-exchange-points`).

**Comment by wis** [comment]
when will I stop forgetting that this such of weird behavior is only explained with the order of the lines in the config file, moving these lines to the end of the file (after loading the plugin with: `zplug "b4b4r07/zsh-vimode-visual", defer:3`) fixes the issue.
edit: no need to unbind before, "overbind": 
```
bindkey -M vivis 'o' vi-visual-forward-char
bindkey -M vivis 'n' vi-visual-backward-char
```

**Comment by babarot** [comment]
🙆 

Please let me know if something happens again
