### ISSUE TITLE
How to install with Oh My Zsh

### ISSUE THREAD

**Issue by ajaydwarkani** [b4b4r07/zsh-vi-mode-visual#12]
I have tried the manual step but that didn't work for me. I am using oh-my-zsh and cloned it under `~/.oh-my-zsh/custom/plugins/zsh-vimode-visual` 

Here is my .zshrc configuration
```
plugins=(
    vi-mode
    zsh-vimode-visual
)
```
I have also tried to use `source` command on terminal but it still didn't work.

**Comment by babarot** [comment]
Unfortunately I have no idea because i'm not oh-my-zsh user. Maybe this plugin will work fine because [zsh-vimode-visual.plugin.zsh](https://github.com/b4b4r07/zsh-vimode-visual/blob/master/zsh-vimode-visual.plugin.zsh) is provided. Please ask to oh-my-zsh repo.
