### ISSUE TITLE
Support for oh-my-zsh users

### ISSUE THREAD

**Issue by Nyquase** [b4b4r07/zsh-vi-mode-visual#8]
Add a zsh-vimode-visual.plugin.zsh file that sources zsh-vimode-visual.zsh
Like https://github.com/zsh-users/zsh-autosuggestions

That way, oh-my-zsh users can just clone the repo in ~/.oh-my-zsh/custom/plugins and activate the plugin like this :
plugin=(... zsh-vimode-visual ...)

**Comment by babarot** [comment]
OK, could you send it as PR?

**Comment by babarot** [comment]
https://github.com/b4b4r07/zsh-vimode-visual/pull/9

Merged, thanks
